Камень судьбы
htmlacademy-yii/1637193-task-force-2 pull request #3
Opened 2021-07-27 14:00 UTC by al-galkin

---
:mortar_board: [Камень судьбы](https://up.htmlacademy.ru/yii/2/user/1637193/tasks/3)

2021-07-27 14:38 UTC, mihan007 requested changes
Рекомендую
1. Перейти на enum точно
2. Ознакомиться детальнее с понятием final state machine, посмотреть ее реализации на php. Брать в использование одну из них в проект или нет - решать тебе. Но многие моменты, если будешь реализовывать самостоятельно, я бы там подсмотрел. Там и удобные форматы хранения состояний и переходов, и многое другое.
- https://symfony.com/doc/current/workflow/workflow-and-state-machine.html
- https://github.com/winzou/state-machine
- https://finite.readthedocs.io/en/master/

2021-07-27 14:38 UTC, mihan007 commented on TaskStatus.php
> +    public function __construct($implementerId, $customerId)
1. php 8.0 к нам пришел. потому давай уже с ним https://stitcher.io/blog/constructor-promotion-in-php-8
2. задавай типы входных данных прямо в коде, это даст гарантию типизации и избавит от лишних phpdoc

2021-07-27 14:38 UTC, mihan007 commented on TaskStatus.php
> +class TaskStatus
1. все эти статусы и экшены по сути являются enum. поэтому самым опытным ребятам я рекомендую использовать https://github.com/spatie/enum и оформить статусы и экшены как enum
2. более того на подходе php 8.1 с нативными enums: https://stitcher.io/blog/php-81-before-and-after#enums

мы ведь идем путем джедаев и будем делать по красоте?) поэтому переделываем на enum - пока через package

2021-07-27 14:38 UTC, mihan007 commented on TaskStatus.php
> +    public function getNextStatus($action): string
1. модель перехода из статуса в статус при выполнении определенных действий называется state machine https://habr.com/ru/company/yandex_praktikum/blog/564800/
2. с ее интересной реализацией можно познакомиться в https://finite.readthedocs.io/en/master/

2021-07-27 14:38 UTC, mihan007 commented on TaskStatus.php
> +        switch ($status) {
вот тут точно надо разделить. у тебя будет две стейт машины: одна с точки зрения исполнителя, другая с точки зрения заказчика. в одной функции через какое-то время начнется дичь

2021-07-27 14:38 UTC, mihan007 commented on test_taskstatus.php
> +$task_status = new TaskStatus(1, 2);
даже в тесте magic numbers - зло. что такое 1? и что такое 2? вынеси их в константы с понятными именами, пожалуйста

2021-07-28 08:31 UTC, al-galkin commented on TaskStatus.php
> +            self::STATUS_UNDER_CONSIDERATION => 'Исполнитель на рассмотрении заказчиком', //todo вопрос: не создал ли двоящийся статус?
собственно вопрос, не лишние ли статусы?

2021-07-29 07:48 UTC, mihan007 requested changes
Продолжаем работу

2021-07-29 07:48 UTC, mihan007 commented on src/Task/ActionOption.php
> +    //todo вопрос: оставить константы? видел внутри enum, что там заглавные переводит в мелкие буквы при вызове функций из статусов
не, константы не нужны. если хочется фиксированные values, то юзай https://github.com/spatie/enum#enum-values

2021-07-29 07:48 UTC, mihan007 commented on src/Task/StateMachine/CustomerStateMachine.php
> +        //todo вопрос: а надо ли как-то зашить действие "создать задачу"? или это будет потом отдельно?
нет, не надо. у тебя задача уже будет появляться со статусом new

2021-07-29 07:48 UTC, mihan007 commented on src/Task/StateMachine/CustomerStateMachine.php
> +        $this->transitions[ActionOption::CANCEL()] = ['from' => TaskStatus::NEW(), 'to' => TaskStatus::CANCELLED()];
может быть можно в одном массиве определить все переходы? или так с ключами-объектами он не дает?
```
$this->transitions = [
    ActionOption::CANCEL(): ['from' => ..., 'to' => ...],
    ActionOption::COMPLETE(): ['from' => ..., 'to' => ...],
]

2021-07-29 07:48 UTC, mihan007 commented on src/Task/StateMachine/StateMachine.php
> +    public function getNextStatus(ActionOption $action): ?TaskStatus
как-то намешано state/status/finite. может оставим просто status везде?

2021-07-29 07:48 UTC, mihan007 commented on src/Task/TaskStatus.php
> +    const NEW = 'new_task';
не нужно. если хочется фиксированные values, то юзай https://github.com/spatie/enum#enum-values

2021-07-29 07:48 UTC, mihan007 commented on src/Task/UserRole.php
> +    //todo надо ли реализовывать методы? или того, что есть достаточно?
тут методы вообще не нужны. это описание типа данных, это даже не полноценный класс. класс он вынуждено пока на уровне языка поддержки enum не завезли.

2021-07-29 07:48 UTC, mihan007 commented on test_taskstatus.php
> +require_once "src/Task/StatefulInterface.php";
с наличием PSR автолоада у тебя require_once будет только один с vendor/autoload. остальное все через use. 

если через use не работает, то, значит, в настройках composer.json автозагрузчика где-то ошибка

2021-07-29 07:48 UTC, mihan007 commented on test_taskstatus.php
> +assert($taskSM->getCurrentState()->label == 'Новая задача', 'возвращает текущий статус');
state/status - ну ты понял, что каша

2021-07-29 07:48 UTC, mihan007 commented on src/Task/TaskStatus.php
> +    protected static function labels(): array
это хорошо и верно, так и надо

2021-07-29 07:48 UTC, mihan007 commented on src/Task/ActionOption.php
> + * @method static self ADD_NEW()
тут необязательно большими буквами. только если тебе нравится.

2021-07-29 07:48 UTC, mihan007 commented on src/Task/ActionOption.php
> +class ActionOption extends \Spatie\Enum\Enum
Название класса ActionOption для Enum нелогично. Я бы назвал TaskActionEnum.

2021-07-29 07:48 UTC, mihan007 commented on composer.json
> +        "yohang/finite": "^1.2"
в composer.json в секция require и require-dev оставляем только то, что используется в коде.

2021-07-29 07:48 UTC, mihan007 commented on composer.json
> +        "codeception/codeception": "*",
codeception и его помощники нужны тебе только при разработке, то есть их точно в require-dev. и то, если используешь. не используешь - убирай, не надо захламлять проект ненужными зависимостями

2021-07-29 07:48 UTC, mihan007 commented on src/Task/StatefulInterface.php
> +    public function setFiniteState(TaskStatus $state): void;
status/state - брррр

2021-07-29 07:48 UTC, mihan007 commented on test_taskstatus.php
> +require_once "src/Task/StatefulInterface.php";
смотри https://getcomposer.org/doc/01-basic-usage.md#autoloading

2021-07-29 11:20 UTC, al-galkin commented on src/Task/StateMachine/CustomerStateMachine.php
> +        $this->transitions[ActionOption::CANCEL()] = ['from' => TaskStatus::NEW(), 'to' => TaskStatus::CANCELLED()];
не, не дает

2021-07-29 11:27 UTC, al-galkin commented
@mihan007 поправил все по замечаниям выше. Тесты теперь проходят. Остался вопросов по реализации методов - надо ли? или то, что они указаны через "* @method static self" достаточно? 

Если нужно, то просьба прислать пример. Вопросы в todo.

2021-07-29 13:07 UTC, mihan007 requested changes
Еще один совсем малюсенький заход
1. Разобраться с наименование enum
2. открыть для себя `?->`
3. в тесте настроить автолоадинг по PSR вместо require_once

2021-07-29 13:07 UTC, mihan007 commented on src/Task/StateMachine/ImplementorStateMachine.php
> +    { //todo вопрос: надо ли реализовывать функции типа TaskActionEnum::respond() ? если да, то можно пример?
не, не надо

2021-07-29 13:07 UTC, mihan007 commented on src/Task/Task.php
> +            return \TaskForce\Task\UserRole::customer();
определись с наименованием енумов. либо все с суффиксом enum, либо все без него. в данном случае напрашивается `UserRoleEnum`

2021-07-29 13:07 UTC, mihan007 commented on src/Task/Task.php
> +        if ($role !== null && $role->equals(UserRole::customer())) {
смотри, что приехало в язык недавно: `$role?->equals(UserRole::customer())` можно делать и это избавит от `$role !== null`. будет прям красиво.

детальнее https://stitcher.io/blog/php-8-nullsafe-operator

2021-07-29 13:07 UTC, mihan007 commented on test_taskstatus.php
> +require_once "src/Task/StatefulInterface.php";
@al-galkin а чего тут не поправил?

2021-07-30 09:40 UTC, al-galkin commented
@mihan007 вроде бы ничего не забыл. Отдельное спасибо за новинку https://wiki.php.net/rfc/nullsafe_operator (на оф. сайте кстати примеры лучше) и за напоминалку про autoload внутри компосера. Отвык с ним работать, чаще как-то внутренними классами битрикса обхожусь

2021-07-30 17:07 UTC, mihan007 approved these changes
Ура! Добили! Молодцом)

2021-07-30 17:08 UTC, merged