Module2 task2
htmlacademy-yii/1637193-task-force-2 pull request #6
Opened 2021-08-11 12:37 UTC by al-galkin

2021-08-12 04:33 UTC, mihan007 requested changes
1. Я для первого класса Action прокомментировал, в остальных также. У тебя уже есть объект Task, над которым мы будем проводить действия. Его и используй.
2. Вообще есть общее правило, что если у функции больше 3 параметров, то что-то не то происходит. Скорее всего надо подумать. Есть исключения типа конструкторов в Dto, но это точно не тут.

2021-08-12 04:33 UTC, mihan007 commented on src/Task/Action/Cancel.php
> +    protected string $actionDescription = 'Отменить задачу';
Тут название верное, лучше перейти на const

2021-08-12 04:33 UTC, mihan007 commented on src/Task/Action/Cancel.php
> +        return $customerId === $userId && $status === 'new';
1. Статусы то оставь enum, им это очень подходит.  Их точно текстом не надо. Не `$status === 'new', а `$status === TaskStatus::new()`
2. А может быть нам внутрь функции передавать объект Task и от него плясать? В нем ты возьмешь все поля, кроме текущего пользователя
```
protected function hasRights(Task $task, int $currentUserId): bool
{
    return ($task->customerId == $currentUserId) && ($task->status == TaskStatus::new());
}
```

2021-08-12 04:33 UTC, mihan007 commented on src/Task/Action/Cancel.php
> +class Cancel extends TaskAction {
PSR-12 жеж, эта скобка на следующей строке https://mihan007.notion.site/PSR-12-Code-Style-f23d1acfbd5e446f8837aed0c4669e63

Поставь тут галку, если в репо заливаешь через PhpStorm - поможет избежать данной ошибки
![2021-08-12 at 07 20](https://user-images.githubusercontent.com/939122/129137772-49c2f1e8-f1ae-4b72-ac69-03cfb4be95b6.png)

2021-08-12 04:33 UTC, mihan007 commented on src/Task/Action/Cancel.php
> +    protected string $action = 'cancel';
подумать над именем и скорее всего это лучше сделать через const, чтобы можно было использовать ее в другом коде как `Cancel::$ACTION_NAME`

2021-08-14 04:57 UTC, mihan007 requested changes
Забыл тут написать. В https://github.com/al-galkin/1637193-task-force-2/pull/1/files мои идеи по реализации функционала. Изучи, пожалуйста

2021-08-14 04:57 UTC, mihan007 commented on scheme/taskforce.sql
>  CREATE TABLE IF NOT EXISTS `users` (
понравилось как ты поработал с именами таблиц и ключей, очень грамотно переименовал

2021-08-14 04:57 UTC, mihan007 commented on src/Task/Action/CancelAction.php
> +
лишняя пустая строка

2021-08-14 04:57 UTC, mihan007 commented on src/Task/Action/CancelAction.php
> +    public static function getAction(): array
а зачем это? почему просто не использовать экземпляр данного класса?

2021-08-14 07:37 UTC, al-galkin commented
@mihan007 спасибо за код-ревью! Вроде понял, что можно смотреть на проблему не только в лоб, но и сбоку, чтобы увидеть альтернативное решение :)

остались вопросы:
1) при попытке проверить ассерт 
`
assert($taskSM->can($refuseAction, $inWorkTask, $customer_id) == false, 'проверяет недоступное действие');
`
возникает предупреждение:
![image](https://user-images.githubusercontent.com/70695734/129438862-d8034772-bc92-4682-8df9-c996facbc2cd.png)
подскажи плз, как поправить.

2) не проходит ассерт 

`
assert($taskSM->getNextStatus($refuseAction, $inWorkTask, $implementor_id)->label === 'Задача провалена', 'возвращает следующий статус');
`

![image](https://user-images.githubusercontent.com/70695734/129438899-cf94bf1b-3d2a-4f64-a0a8-73d2052598f8.png)


3) не проходит ассерт

`assert($taskSM->getAvailableActions()[0] == $cancelAction, 'возвращает доступные действия');
`

но тут я по-моему с методом StateMachine->getAvailableActions перемудрил. Посмотри пожалуйста эти моменты

![image](https://user-images.githubusercontent.com/70695734/129438923-1e6d35c5-4824-4d6f-ad15-43d3069a48d3.png)

2021-08-15 04:47 UTC, mihan007 requested changes
Привет, Александр! Отличный рефакторинг сделал. Можно еще проще, посмотри комментарии.

2021-08-15 04:47 UTC, mihan007 commented on src/Task/Action/CompleteAction.php
> +
лишняя пустая строка, снижает читаемость. одна строка между функциями максимум.

2021-08-15 04:47 UTC, mihan007 commented on src/Task/StateMachine/StateMachine.php
> +    public function apply(CompleteAction|CancelAction|RefuseAction|RespondAction $action, $task, $currentUserId): void
Здесь лучше подойдет тип базового класса `TaskAction`, так как количество действий может увеличиться

2021-08-15 04:47 UTC, mihan007 commented on src/Task/Action/RespondAction.php
> +        return ($task->implementorId === $currentUserId) && ($task->getStatus() === TaskStatusEnum::new());
`$task->getStatus() === TaskStatusEnum::new()` - эта часть не нужна. ты же внизу уже проверишь `if ($action->transitFromStatus === $task->getStatus())` и тут эта проверка не нужна.

2021-08-17 04:47 UTC, mihan007 commented
@al-galkin отвечаю на вопросы
- Пункты 1 и 3 - смотри два последних коммита https://github.com/htmlacademy-yii/1637193-task-force-2/commits/fixes
- Еще по пункту 2
![01](https://user-images.githubusercontent.com/939122/129664201-98b9d2b2-3903-47a8-a1ba-dfb5e0579424.png)

2021-08-20 09:40 UTC, al-galkin commented
@mihan007 остался вопрос по 1 ассерту (где $nextStatusAfterRefuse):
нарочно подменил в задаче заказчика на исполнителя. По ТЗ отказаться от задачи может только исполнитель, поэтому на заказчика должен срабатывать ассерт. Однако у меня ассерт спокойно проходит дальше. https://skr.sh/s9dRl0YR503 Помоги пожалуйста разобраться, почему не срабатывает ошибка и как поправить

2021-08-23 05:31 UTC, mihan007 approved these changes
멋진 일! 자랑스러운!

2021-08-23 05:31 UTC, mihan007 commented on src/Task/StateMachine/StateMachine.php
> +     * @var array<TaskAction>
прям красавчик

2021-08-23 05:37 UTC, merged

2021-08-23 09:01 UTC, al-galkin commented on src/Task/StateMachine/StateMachine.php
> +     * @var array<TaskAction>
@mihan007 귀하의 광고가 여기에있을 수 있습니다 :)